// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 21.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'vakinhaburger_flutterweb';

  static const String assets_images_icons_cancel_order_white_icon_png = 'assets/images/icons/cancel_order_white_icon.png';
  static const String vakinhaburger_flutterweb$assets_images_icons_cancel_order_white_icon_png = 'packages/vakinhaburger_flutterweb/assets/images/icons/cancel_order_white_icon.png';

  static const String assets_images_icons_client_ico_png = 'assets/images/icons/client_ico.png';
  static const String vakinhaburger_flutterweb$assets_images_icons_client_ico_png = 'packages/vakinhaburger_flutterweb/assets/images/icons/client_ico.png';

  static const String assets_images_icons_client_ico_selected_png = 'assets/images/icons/client_ico_selected.png';
  static const String vakinhaburger_flutterweb$assets_images_icons_client_ico_selected_png = 'packages/vakinhaburger_flutterweb/assets/images/icons/client_ico_selected.png';

  static const String assets_images_icons_confirm_order_icon_png = 'assets/images/icons/confirm_order_icon.png';
  static const String vakinhaburger_flutterweb$assets_images_icons_confirm_order_icon_png = 'packages/vakinhaburger_flutterweb/assets/images/icons/confirm_order_icon.png';

  static const String assets_images_icons_confirm_order_white_icon_png = 'assets/images/icons/confirm_order_white_icon.png';
  static const String vakinhaburger_flutterweb$assets_images_icons_confirm_order_white_icon_png = 'packages/vakinhaburger_flutterweb/assets/images/icons/confirm_order_white_icon.png';

  static const String assets_images_icons_finish_order_ico_png = 'assets/images/icons/finish_order_ico.png';
  static const String vakinhaburger_flutterweb$assets_images_icons_finish_order_ico_png = 'packages/vakinhaburger_flutterweb/assets/images/icons/finish_order_ico.png';

  static const String assets_images_icons_finish_order_white_ico_png = 'assets/images/icons/finish_order_white_ico.png';
  static const String vakinhaburger_flutterweb$assets_images_icons_finish_order_white_ico_png = 'packages/vakinhaburger_flutterweb/assets/images/icons/finish_order_white_ico.png';

  static const String assets_images_icons_order_edit_icon_png = 'assets/images/icons/order_edit_icon.png';
  static const String vakinhaburger_flutterweb$assets_images_icons_order_edit_icon_png = 'packages/vakinhaburger_flutterweb/assets/images/icons/order_edit_icon.png';

  static const String assets_images_icons_order_ico_png = 'assets/images/icons/order_ico.png';
  static const String vakinhaburger_flutterweb$assets_images_icons_order_ico_png = 'packages/vakinhaburger_flutterweb/assets/images/icons/order_ico.png';

  static const String assets_images_icons_order_ico_selected_png = 'assets/images/icons/order_ico_selected.png';
  static const String vakinhaburger_flutterweb$assets_images_icons_order_ico_selected_png = 'packages/vakinhaburger_flutterweb/assets/images/icons/order_ico_selected.png';

  static const String assets_images_icons_payment_cc_icon_png = 'assets/images/icons/payment_cc_icon.png';
  static const String vakinhaburger_flutterweb$assets_images_icons_payment_cc_icon_png = 'packages/vakinhaburger_flutterweb/assets/images/icons/payment_cc_icon.png';

  static const String assets_images_icons_payment_cd_icon_png = 'assets/images/icons/payment_cd_icon.png';
  static const String vakinhaburger_flutterweb$assets_images_icons_payment_cd_icon_png = 'packages/vakinhaburger_flutterweb/assets/images/icons/payment_cd_icon.png';

  static const String assets_images_icons_payment_notfound_icon_png = 'assets/images/icons/payment_notfound_icon.png';
  static const String vakinhaburger_flutterweb$assets_images_icons_payment_notfound_icon_png = 'packages/vakinhaburger_flutterweb/assets/images/icons/payment_notfound_icon.png';

  static const String assets_images_icons_payment_type_ico_png = 'assets/images/icons/payment_type_ico.png';
  static const String vakinhaburger_flutterweb$assets_images_icons_payment_type_ico_png = 'packages/vakinhaburger_flutterweb/assets/images/icons/payment_type_ico.png';

  static const String assets_images_icons_payment_type_ico_selected_png = 'assets/images/icons/payment_type_ico_selected.png';
  static const String vakinhaburger_flutterweb$assets_images_icons_payment_type_ico_selected_png = 'packages/vakinhaburger_flutterweb/assets/images/icons/payment_type_ico_selected.png';

  static const String assets_images_icons_payment_va_icon_png = 'assets/images/icons/payment_va_icon.png';
  static const String vakinhaburger_flutterweb$assets_images_icons_payment_va_icon_png = 'packages/vakinhaburger_flutterweb/assets/images/icons/payment_va_icon.png';

  static const String assets_images_icons_payment_vr_icon_png = 'assets/images/icons/payment_vr_icon.png';
  static const String vakinhaburger_flutterweb$assets_images_icons_payment_vr_icon_png = 'packages/vakinhaburger_flutterweb/assets/images/icons/payment_vr_icon.png';

  static const String assets_images_icons_product_ico_png = 'assets/images/icons/product_ico.png';
  static const String vakinhaburger_flutterweb$assets_images_icons_product_ico_png = 'packages/vakinhaburger_flutterweb/assets/images/icons/product_ico.png';

  static const String assets_images_icons_product_ico_selected_png = 'assets/images/icons/product_ico_selected.png';
  static const String vakinhaburger_flutterweb$assets_images_icons_product_ico_selected_png = 'packages/vakinhaburger_flutterweb/assets/images/icons/product_ico_selected.png';

  static const String assets_images_lanche_png = 'assets/images/lanche.png';
  static const String vakinhaburger_flutterweb$assets_images_lanche_png = 'packages/vakinhaburger_flutterweb/assets/images/lanche.png';

  static const String assets_images_logo_png = 'assets/images/logo.png';
  static const String vakinhaburger_flutterweb$assets_images_logo_png = 'packages/vakinhaburger_flutterweb/assets/images/logo.png';
}
